services:
  db:
    image: mysql:8

    volumes:
      - ./remo-backend/src/migrations/:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql
    ports:
      # mapping host port 3200 to container port 3306
      - 3333:3306

    restart: unless-stopped
    environment:
      MYSQL_USER: remo
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remodb
volumes:
  db:
    driver: local