// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewBook struct {
	ID            string `json:"id"`
	DefaultUserID int    `json:"default_user_id"`
}

type NewClassroom struct {
	ClassroomID          string `json:"classroom_id"`
	ClassroomCoTeacherID string `json:"Classroom_co_teacher_id"`
	ClassroomStatusID    string `json:"classroom_status_id"`
}

type NewStudent struct {
	ID           string `json:"id"`
	StudentID    string `json:"Student_id"`
	StudentAppID string `json:"student_app_id"`
	FirstName    string `json:"First_name"`
	MiddleName   string `json:"Middle_name"`
	LastName     string `json:"last_name"`
}

type NewTeacher struct {
	ID                   string    `json:"id"`
	ClassroomCoTeacherID string    `json:"classroom_co_teacher_id"`
	ClassroomStatusID    string    `json:"classroom_status_id"`
	TeacherFirstName     string    `json:"Teacher_first_name"`
	TeacherLastName      string    `json:"Teacher_last_name"`
	Active               int       `json:"Active"`
	TeacherDateCreated   time.Time `json:"Teacher_date_created"`
	TeacherDateUpdated   time.Time `json:"Teacher_date_updated"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type NewReadingRateResults struct {
	ReadingRateResultsID string `json:"Reading_rate_results_id"`
}
