// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBook struct {
	Title  string `json:"title"`
	Author string `json:"author"`
	UserID string `json:"userId"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}
